### ISSUE TITLE
regex and lf

### ISSUE THREAD

**Issue by LukeWCS** [GerB/modbreak#5]
https://github.com/GerB/modbreak/blob/c8ef4f2181ae168e79a553cee2d9e728eba4b029/event/main_listener.php#L87

Before your change I didn't know that LF's _inside_ a BBcode tag are allowed. Interessting. ^^ Ok, then you can also remove (?s), because this modifier allows LF's, but only _between_ the tags, not inside. So with /is the modifier (?s) is no longer needed.

**Comment by GerB** [comment]
There are several, could you send a PR with the correct regex? Saves me some trial and error :)

**Comment by LukeWCS** [comment]
Ah, okay, no problem. Then I send it with b3. Ger, is it okay for you that we use a tab size of 4 globally in our both ModBreak repos?

**Comment by GerB** [comment]
I don't mind actually, I have my IDE set to only save tabs. Alt + Shift + F usually does the trick to auto-format as desired. It might be that I have forgotten that in some files.

**Comment by LukeWCS** [comment]
Yes it depends to the used IDE/Editor. In my own editor I use normally tab4 for php, css, js, html, pl, pm etc. I mean the GH Web Interface, the default is tab8 but there is a easy way to force GH Web to use another tab width. You will see it with the next PR.

**Comment by LukeWCS** [comment]
Ger, your change with "/is" broke something. There are now cases which mbx produce wrong results. I need some time to sort this out.

**Comment by LukeWCS** [comment]
Phew, that regex thing cost me nerves. Now it's more flexible (like "/is") and more robust. Please don't add "/is". ^^ With my prepared test posting all is okay. I will do more tests now and then I push build 3.

**Comment by GerB** [comment]
Merged it, thanks!
